### ISSUE TITLE
VALARM not handle correctly

### ISSUE THREAD

**Issue by xbgmsharp** [dupondje/PHP-Push-2#5]
When i sync from the caldav server to the mobile there is an with the ALARM.
In a result there is an reminder on the phone set to 'at the time of the event' but it was not.
When sync back to the server the entry does not have any more any reminder set.

BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT1H
ACTION:DISPLAY
END:VALARM
SEQUENCE:1

Or this one
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT5M
DESCRIPTION:Mozilla Standardbeschreibung
END:VALARM

BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT10M
ACTION:DISPLAY
END:VALARM

ActiveSync only support alarm in minutes
DateInterval does not convert time in minutes.

The log show:
CaldavBackend: _ParseVEventToSyncObject[_ParseVEventToSyncObject(): 'VALARM': [DURATION] [-PT5M].]
CaldavBackend: _ParseVEventToSyncObject[_ParseVEventToSyncObject(): 'VALARM': [PT5M].]
CaldavBackend: _ParseVEventToSyncObject[_ParseVEventToSyncObject(): 'VALARM': [5].]

To make it work, replace:
$message->reminder = $interval->format("i");
by:
$message->reminder = $interval->format("%i");
However it won't convert hours in minutes

**Comment by dupondje** [comment]
Fixed.

Hours are also handled now.

Thanks!

**Comment by xbgmsharp** [comment]
Thanks for prompt reply.
Still missing the D (day) and W (week) parsing.
This would fix the day.
$message->reminder = $interval->format("%i") + $interval->format("%h") \* 60 + $interval->format("%d") \* 24;
The problem now is too handle the week (W) but as a week is 7 days it should be fine.

**Comment by xbgmsharp** [comment]
Sorry should be:
message->reminder = $interval->format("%i") + $interval->format("%h") _60 + $interval->format("%d") *24_60;

**Comment by dupondje** [comment]
-                                               $message->reminder =
  $interval->format("%i") + $interval->format("%h") \* 60;
-                                               $message->reminder =
  $interval->format("%i") + $interval->format("%h") \* 60 +
  $interval->format("%a") \* 60 \* 24;

This should be perfect :)
%a gives amount in days (unlimited), so 2 weeks it will return 14 :)

Committed!
Thx

Op 23-05-12 14:34, xbgmsharp schreef:
